proyecto/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from proyecto import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'proyecto'


urlpatterns = [
    url(r'^$',views.vista_index, name="vista_index"),
    #PROYECTO
    url(r'^crear_proyecto/$', views.vista_crear_proyecto, name="vista_crear_proyecto"),
    url(r'^(?P<idP>\d+)/consultar_proyecto$', views.vista_consultar_proyecto, name="vista_consultar_proyecto"),
    url(r'^listar_proyectos/$', views.vista_listar_proyectos, name="vista_listar_proyectos"),
    url(r'^(?P<idP>\d+)/modificar_proyecto/$', views.vista_modificar_proyecto, name="vista_modificar_proyecto"),
    url(r'^eliminar_proyecto/$', views.vista_eliminar_proyecto, name="vista_eliminar_proyecto"),
    url(r'^mis_proyectos/$', views.vista_mis_proyectos, name="vista_mis_proyectos"),
    url(r'^(?P<idP>\d+)/agregar_participantes/$', views.vista_agregar_participantes, name="vista_agregar_participantes"),
    url(r'^(?P<idP>\d+)/cancelar_proyecto/$', views.vista_cancelar_proyecto, name="vista_cancelar_proyecto"),
    url(r'^(?P<idP>\d+)/retomar_proyecto/$', views.vista_retomar_proyecto, name="vista_retomar_proyecto"),
    url(r'^(?P<idP>\d+)/finalizar_proyecto/$', views.vista_finalizar_proyecto, name="vista_finalizar_proyecto"),
    url(r'^(?P<idP>\d+)/modificar_SM/$', views.vista_modificar_SM, name="vista_modificar_SM"),

    #USUARIOS
    url(r'^(?P<getIdUsuario>[0-9]+)/ver_usuario/$', views.vista_verUsuario, name="vista_verUsuario"),
    url(r'^lista_usuarios', views.vista_listaUsuarios, name="vista_listaUsuarios"),
    url(r'^(?P<getIdUsuario>[0-9]+)/editar_usuario/$', views.vista_editarUsuario, name="vista_editarUsuario"),
    url(r'^nuevo_usuario/$', views.vista_nuevoUsuario, name="vista_nuevoUsuario"),
    url(r'^eliminar_usuario/$', views.vista_eliminarUsuario, name="vista_eliminarUsuario"),
    url(r'^(?P<getIdUsuario>[0-9]+)/cambiar_contrasenha/$', views.vista_cambiarContrasenha, name="vista_cambiarContrasenha"),

    #PERMISOS
    url(r'^lista_permisos', views.vista_listaPermisos, name="vista_listaPermisos"),
    url(r'^nuevo_permiso/$', views.vista_nuevoPermiso, name="vista_nuevoPermiso"),
    url(r'^(?P<getIdPermiso>[0-9]+)/ver_permiso/$', views.vista_verPermiso, name="vista_verPermiso"),
    url(r'^(?P<getIdPermiso>[0-9]+)/editar_permiso/$', views.vista_editarPermiso, name="vista_editarPermiso"),

    #ROLES
    url(r'^(?P<getIdRol>[0-9]+)/ver_rol/$', views.vista_verRol, name="vista_verRol"),
    url(r'^lista_roles', views.vista_listaRoles, name="vista_listaRoles"),
    url(r'^nuevo_rol/$', views.vista_nuevoRol, name="vista_nuevoRol"),
    url(r'^(?P<getIdRol>[0-9]+)/editar_rol/$', views.vista_editarRol, name="vista_editarRol"),

    #USER STORY
    url(r'^(?P<idP>[0-9]+)/nuevo_us/$', views.vista_crear_userstory, name="vista_crear_userstory"),
    url(r'^eliminar_us/$', views.vista_eliminarUS, name="vista_eliminarUS"),
    url(r'^(?P<idP>[0-9]+)/consultar_us/(?P<idUs>[0-9]+)/$', views.vista_consultar_us, name="vista_consultar_us"),
    url(r'^(?P<idP>[0-9]+)/lista_us/$', views.vista_lista_us, name="vista_lista_us"),
    url(r'^(?P<idP>[0-9]+)/modificar_us/(?P<idUs>[0-9]+)/$', views.vista_modificar_us, name="vista_modificar_us"),
    #url(r'^(?P<idP>[0-9]+)/agregar_developer_us/(?P<idUs>[0-9]+)/$', views.vista_agregar_developer_us, name="vista_agregar_developer_us"), se paso a la parte de Sprint
    url(r'^(?P<idP>[0-9]+)/avance_us/(?P<idUs>[0-9]+)/$', views.vista_registrar_avance_us, name="vista_registrar_avance_us"),
    url(r'^(?P<idP>[0-9]+)/subir_archivo/(?P<idUs>[0-9]+)/$', views.vista_subirArchivo, name="vista_subirArchivo"),
    url(r'^eliminar_archivo/$', views.vista_eliminarArchivo, name="vista_eliminarArchivo"),
    url(r'^eliminar_nota/$', views.vista_eliminarNota, name="vista_eliminarNota"),

    #formularios
    url(r'^eliminar_permiso/$', views.vista_eliminarPermiso, name="vista_eliminarPermiso"),
    url(r'^eliminar_rol/$', views.vista_eliminarRol, name="vista_eliminarRol"),

    #SPRINTS
    url(r'^(?P<idP>[0-9]+)/crear_sprint/$', views.vista_crear_sprint,name="vista_crear_sprint"),
    url(r'^(?P<idP>[0-9]+)/lista_sprint', views.vista_lista_sprint, name="vista_lista_sprint"),
    url(r'^(?P<idP>[0-9]+)/consultar_sprint/(?P<idS>[0-9]+)$', views.vista_consultar_sprint, name="vista_consultar_sprint"),
    url(r'^(?P<idP>[0-9]+)/modificar_sprint/(?P<idS>[0-9]+)$', views.vista_modificar_sprint, name="vista_modificar_sprint"),
    url(r'^eliminar_sprint/$', views.vista_eliminar_sprint, name="vista_eliminar_sprint"),
    url(r'^(?P<idP>[0-9]+)/agregar_us/(?P<idS>[0-9]+)$', views.vista_agregar_us, name="vista_agregar_us"),
    url(r'^(?P<idP>[0-9]+)/agregar_developers_sprint/(?P<idS>[0-9]+)$', views.vista_agregar_developer_sprint, name="vista_agregar_developer_sprint"),
    url(r'^(?P<idP>[0-9]+)/agregar_developer_us/(?P<idS>[0-9]+)/(?P<idUs>[0-9]+)/$', views.vista_agregar_developer_us, name="vista_agregar_developer_us"),
    url(r'^(?P<idP>[0-9]+)/agregar_horas_trabajo_sprint/(?P<idS>[0-9]+)$', views.vista_asignar_horas_trabajo, name="vista_asignar_horas_trabajo"),
    url(r'^(?P<idP>[0-9]+)/ejecutar_sprint/(?P<idS>[0-9]+)$', views.vista_ejecutar_sprint, name="vista_ejecutar_sprint"),
    url(r'^finalizar_sprint/$', views.vista_finalizar_sprint, name="vista_finalizar_sprint"),

    #flujos
    url(r'^(?P<idP>[0-9]+)/lista_flujos', views.vista_listaFlujos, name="vista_listaFlujos"),
    url(r'^(?P<idP>[0-9]+)/nuevo_flujo/$', views.vista_nuevoFlujo, name="vista_nuevoFlujo"),
    url(r'^ver_flujo/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_verFlujo, name="vista_verFlujo"),
    url(r'^editar_flujo/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_editarFlujo, name="vista_editarFlujo"),
    url(r'^editar_estadoUS/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/(?P<idUs>[0-9]+)/$', views.vista_editarEstadoUS, name="vista_editarEstadoUS"),
    url(r'^editar_actividad/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/(?P<idActividad>[0-9]+)/$', views.vista_editarActividad,name="vista_editarActividad"),
    url(r'^agregar_us_a_flujo/(?P<idP>[0-9]+)/(?P<idUS>[0-9]+)/(?P<idS>[0-9]+)$', views.vista_agregarUSaFlujo,name="vista_agregarUSaFlujo"),

    #kanban
    url(r'^lista_kanban/(?P<idP>[0-9]+)/$', views.vista_listaKanban, name="vista_listaKanban"),
    url(r'^ver_kanban/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_verKanban, name="vista_verKanban"),
]

sgp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("autenticacion.urls", namespace='autenticacion')),
    url(r'^', include("proyecto.urls", namespace='proyecto')),
]

proyecto/views/flujo_views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render
from proyecto.forms import *
from proyecto.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.utils.datastructures import MultiValueDictKeyError
import datetime
from django.db.models import Max

@login_required
@csrf_protect
def vista_nuevoFlujo(request, idP):
    """
        La funcion vista "Nuevo Flujo_Proyecto" presenta un formulario para ingresar los datos de un nuevo flujo.
        Una vez creado el flujo exitosamente, redirecciona con alerta de confirmacion.
        @param request:
        @param idP: id del Proyecto.
        @return: Redirecciona a la lista de flujos, y presenta una alerta de confirmacion.
        """
    proyecto = Proyecto.objects.get(id=idP)
    usuario = Usuario.objects.get(user=request.user)
    # Chutar a usuario sin permisos
    if not usuario.tienePermiso(proyecto, 'crear_flujo'):
        return HttpResponseRedirect('/')
    if request.method != 'POST':
        idUs = Product_Backlog.objects.filter(proyecto=proyecto).values_list('us_id', flat=True)
        idUs = Flujo_Us.objects.filter(us_id__in=idUs).values_list('us_id', flat=True)
        idUs = Product_Backlog.objects.exclude(proyecto=proyecto, us_id__in=idUs).values_list('us_id', flat=True)
        lista_us = UserStory.objects.order_by('id').filter(id__in=idUs)


        # obtener permisos de un usuario
        permisosAsociados = proyecto.getListaPermisosDeUsuario(request.user)
        return render(request, "html/flujos/nuevoFlujo.html", {'lista_us': lista_us,
                                                               'idP': idP,
                                                               'permisosAsociados': permisosAsociados,
                                                               'proyecto': proyecto,

                                                               })


    flujo = Flujo_Proyecto.objects.create(proyecto=proyecto,descripcion=request.POST['descripcionFlujo'])

    # procesar las actividades
    # Obtener nombre de checkboxes chequeados, procesar y guardar
    lista_checks_actividades = request.POST.getlist('chkActividades')
    cont = 1
    listaActividades = []
    for descripcionActividad in lista_checks_actividades:
        Actividad.objects.create(
            flujo=flujo,
            orden=cont,
            descripcion=descripcionActividad)
        cont = cont + 1

    # Registrar en log
    Log_Flujo.objects.create(flujo=flujo,
                             descripcion="Se ha creado el flujo.")

    messages.success(request, "Se creo exitosamente el flujo")

    return HttpResponseRedirect(reverse('proyecto:vista_listaFlujos', args=[idP]))


@login_required
def vista_listaFlujos(request, idP):
    """
        La funcion vista "Lista Flujos" presenta la lista de todos los flujos registrados.
        @param request:
        @param idP: id del Proyecto.
        @return: Renderiza el html encargado de presentar la lista de flujos del proyecto.
        """
    proyecto = Proyecto.objects.get(id=idP)
    usuario = Usuario.objects.get(user=request.user)
    # Chutar a usuario sin permisos
    if not usuario.tienePermiso(proyecto, 'ver_lista_flujos'):
        return HttpResponseRedirect('/')
    lista_flujos = Flujo_Proyecto.objects.order_by('id').filter(proyecto=proyecto)
    # obtener permisos de un usuario
    permisosAsociados = proyecto.getListaPermisosDeUsuario(request.user)
    return render(request, "html/flujos/listaFlujos.html", {'lista_flujos': lista_flujos,
                                                            'proyecto': proyecto,
                                                            'idP': idP,
                                                            'permisosAsociados': permisosAsociados,
                                                            })


@login_required
def vista_verFlujo(request, idP, idFlujo):
    """
        La funcion vista "Ver Flujo_Proyecto" presenta los detalles de un flujo cuyo id se recibe por parámetro.
        También recibe el id del Proyecto asociado al mismo.
        @param request:
        @param idFlujo: ID del flujo
        @param idP: ID del proyecto
        @return: Renderiza el html encargado de presentar los detalles del flujo.
        """
    proyecto = Proyecto.objects.get(id=idP)
    usuario = Usuario.objects.get(user=request.user)
    # Chutar a usuario sin permisos
    if not usuario.tienePermiso(proyecto, 'ver_flujo'):
        return HttpResponseRedirect('/')
    # obtener permisos de un usuario

    permisosAsociados = proyecto.getListaPermisosDeUsuario(request.user)
    flujo = get_object_or_404(Flujo_Proyecto, id=idFlujo)

    lista_actividades = Actividad.objects.order_by('orden').filter(flujo=flujo)
    idUs = Flujo_Us.objects.filter(flujo=flujo).values_list('us_id', flat=True)
    lista_actividad_us = Actividad_Us.objects.order_by('id').filter(us_id__in=idUs)
    listaActividadUS=[]
    #comprobar si el sprint en donde esta el us ya inicio
    for au in lista_actividad_us:
        try:
            sprint=Proyecto_Sprint_Us.objects.get(proyecto=proyecto,us=au.us).sprint
            listaActividadUS.append([au,sprint.estaEnEjecucion()])
        except Proyecto_Sprint_Us.DoesNotExist:
            sprint = None


    # enviar lista de us en los que el usuario es developer
    usuario = Usuario.objects.get(user=request.user)

    idListaUS = Product_Backlog.objects.filter(proyecto=proyecto, usuario=usuario).values_list('us_id', flat=True)
    lista_us_esDeveloper = UserStory.objects.filter(id__in=idListaUS)

    # obtener lista de US actuales del flujo para enviar a los checks del form
    usActuales = UserStory.objects.filter(id__in=idUs)

    #obtener log del flujo
    lista_log=Log_Flujo.objects.order_by('id').filter(flujo=flujo)
    #obtener ultima actividad del flujo
    try:
        ultimaActividad= Actividad.objects.filter(flujo=flujo).latest('orden')
    except Actividad.DoesNotExist:
        ultimaActividad=False

    return render(request, "html/flujos/verFlujo.html", {'flujo': flujo,
                                                         'lista_actividades': lista_actividades,
                                                         'lista_actividad_us': listaActividadUS,
                                                         'idP': idP,
                                                         'ultimaActividad': ultimaActividad,
                                                         'permisosAsociados': permisosAsociados,
                                                         'proyecto': proyecto,
                                                         'lista_us_esDeveloper': lista_us_esDeveloper,
                                                         'usActuales': usActuales,
                                                         'lista_log':lista_log,

                                                         })


@login_required
@csrf_protect
def vista_editarFlujo(request, idP, idFlujo):
    """
        La funcion vista "Editar Flujo_Proyecto" presenta un formulario para modificar los datos actuales de un flujo
        cuyo ID se recibe por parámetro.
        @param request:
        @param idFlujo: ID del proyecto
        @param idFlujo: ID del flujo
        @return: Redirecciona a la vista "Lista de Flujos", con alerta de confirmacion de cambios.
        """
    proyecto = Proyecto.objects.get(id=idP)
    usuario = Usuario.objects.get(user=request.user)
    # Chutar a usuario sin permisos, tambien chutar si es que ya hay us en el flujo

    if not usuario.tienePermiso(proyecto, 'editar_flujo'):
        return HttpResponseRedirect('/')
    if request.method == 'POST':

        flujo = Flujo_Proyecto.objects.get(id=idFlujo)
        flujo.descripcion = request.POST['descripcionFlujo']

        flujo.save()
        # Obtener nombre de checkboxes chequeados en Actividades
        try:

            lista_checks_actividades = request.POST.getlist('chkActividades')

            # reorganizar actividades que ya estan guardadas

            # pueden haber dos tipos de valores recibidos> un ID si actividad ya existe
            # o un string de descripcion si es que aun no existe dicha actividad

            # verificar los Ids y setear el orden de los mismos
            cont = 1
            for actividad in lista_checks_actividades:
                try:
                    a = Actividad.objects.get(id=actividad)
                    a.orden = cont
                    a.save()

                except ValueError:
                    # se han ingresado nuevas actividades, por tanto se recibio un string
                    Actividad.objects.create(flujo=flujo, orden=cont, descripcion=actividad)
                cont = cont + 1
        except MultiValueDictKeyError:
            print ""

        # procesar los us
        lista_checks_us = request.POST.getlist('chkUs')
        for iDus in lista_checks_us:
            us = UserStory.objects.get(id=iDus)
            flujoUs = Flujo_Us(flujo=flujo, us=us)
            flujoUs.save()

            # relacionar actividad con estado inicial
            actividad = Actividad.objects.get(flujo=flujo, orden=1)
            au = Actividad_Us(actividad=actividad, us=us, estado='TD')
            au.save()
        # Registrar en log
        Log_Flujo.objects.create(flujo=flujo,
                                     descripcion="Se ha modificado los datos del flujo.")
        messages.success(request, "Se modificó exitosamente el flujo")

templates/html/flujos/anhadirUSaFlujo.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    AnhadirUsaFlujo
{% endblock %}
{% block header %}

{% endblock %}
{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Añadir US a flujo
                <small></small>
            </h1>
             <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                            </li>
                            {% if request.user.is_staff %}
                             <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de Proyectos</a>
                            </li>
                            {% else %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_mis_proyectos' %}">Mis Proyectos</a>
                            </li>
                            {% endif %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_proyecto' proyecto.id %}">Consulta Proyecto</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_lista_sprint' idP %}">Sprint Backlog</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_sprint' idP idS %}">Consulta de Sprint</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-list"></i>Añadir US a Flujo
                            </li>

            </ol>
        </div>
        <div class="col-lg-6">

            <form action="" method="post">
            {% csrf_token %}
                <select class="form-control" name="idFlujo">
                    {% for flujo in listaFlujos %}

                        <option value="{{ flujo.id }}">{{ flujo.descripcion }}</option>
                    {% endfor %}
                </select>
            <br>
                <button type="submit" class="btn btn-success">Guardar</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/html/flujos/editarActividad.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    detalles Actividad
{% endblock %}
{% block header %}

{% endblock %}
{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Detalles de actividad
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                </li>
                <li>
                    <i class="fa fa-table"></i> <a href="{% url 'proyecto:vista_listaFlujos' proyecto.id %}">Lista de
                    Flujos</a>
                </li>
                <li>
                    <i class="fa fa-table"></i> <a href="{% url 'proyecto:vista_verFlujo' idP idFlujo %}">Detalle del
                    Flujo</a>
                </li>
                <li>
                    <i class="fa fa-edit"></i> <a href="{% url 'proyecto:vista_editarFlujo' idP idFlujo %}">Editar
                    Flujo</a>
                </li>
                <li class="active">
                    <i class="fa fa-edit"></i>Editar nombre de la actividad</i>
                </li>
            </ol>
        </div>
        <div class="col-lg-6">
            {% if msj_error %}
                <div class="alert alert-danger">
                    <strong>Error!</strong> {{ msj_error }}
                </div>
            {% endif %}
            {% if msj_ok %}
                <div class="alert alert-success">
                    <strong>OK!</strong> {{ msj_ok }}
                </div>
            {% endif %}
            <form id="formEditarUsuario" action="" method="post">
                {% csrf_token %}
                <label>Nombre de actividad</label>
                <input class="form-control" name="nombre" id="nombre" value="{{ actividad.descripcion }}">
                <br>
                <button type="submit" class="btn btn-success">Guardar</button>
                <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_verFlujo' idP idFlujo %}">Cancelar</a>

            </form>
        </div>
    </div>

{% endblock %}

templates/html/flujos/verFlujo.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    Ver Flujo
{% endblock %}
{% block header %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if 'warning' in message.tags %}
                    <script> generate('warning', "{{ message }}");</script>
                {% endif %}
                {% if 'success' in message.tags %}
                    <script> generate('success', "{{ message }}");</script>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}
{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Detalles del flujo
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                </li>

                <li>
                    <i class="fa fa-table"></i> <a href="{% url 'proyecto:vista_listaFlujos' proyecto.id %}">Lista de
                    Flujos</a>
                </li>
                <li class="active">
                    <i class="fa fa-edit"></i> Detalles de flujo
                </li>
            </ol>

            {% if msj_error %}
                <div class="alert alert-danger">
                    <strong>Error!</strong> {{ msj_error }}

                </div>
            {% endif %}
            {% if msj_ok %}
                <div class="alert alert-success">
                    <strong>OK!</strong> {{ msj_ok }}

                </div>
            {% endif %}

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> Titulo</h3>
                </div>
                <div class="panel-body">
                    <li><strong>Id:</strong> {{ flujo.id }}</li>
                    <br>
                    <li><strong>Descripción:</strong> {{ flujo.descripcion }}</li>
                    <br>

                    <li><strong>Lista de Actividades del flujo:</strong></li>
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <th>
                                <center>Secuencia en el flujo</center>
                            </th>
                            <th>
                                <center>Descripción</center>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for actividad in lista_actividades %}
                            <tr>
                                <td>
                                    <center>{{ actividad.orden }}</center>
                                </td>
                                <td>
                                    <center>{{ actividad.descripcion }}</center>
                                </td>

                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                    <br>
                    <li><strong>Lista de User Stories del flujo:</strong></li>
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <th>
                                <center>Descripción corta</center>
                            </th>
                            <th>
                                <center>Descripción larga</center>
                            </th>
                            <th>
                                <center>Actividad actual del User Story</center>
                            </th>
                            <th>
                                <center>Estado dentro de la actividad</center>
                            </th>
                            <th>
                                <center>User Story</center>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for actividad_us in lista_actividad_us %}
                            <tr>
                                <td>
                                    <center><a href="{% url 'proyecto:vista_consultar_us' idP actividad_us.0.us.id %}" data-toggle="tooltip" title="Consultar detalles del User Story">{{ actividad_us.0.us.descripcion_corta }}</a></center>
                                </td>
                                <td>
                                    <center>{{ actividad_us.0.us.descripcion_larga }}</center>
                                </td>
                                <td>
                                    <center>{{ actividad_us.0.actividad.descripcion }}</center>
                                </td>
                                <td>
                                    <center>{{ actividad_us.0.get_estado_verbose }}</center>
                                </td>
                                <td>

                                    {% if actividad_us.1 == False%}
                                                El sprint de este US aún no está en ejecución.
                                    {% endif %}

                                    {% if 'editar_estado_us_scrum' in permisosAsociados and actividad_us.1 %}
                                        <center><a class="btn btn-sm btn-default"
                                                   href="{% url 'proyecto:vista_editarEstadoUS' idP flujo.id actividad_us.0.us.id %}"
                                        >Modificar estado
                                        </a>

                                        </center>
                                    {% else %}
                                    {% if actividad_us.0.us in lista_us_esDeveloper %}
                                        {% if actividad_us.actividad == ultimaActividad and actividad_us.get_estado_verbose == 'Done' %}
                                        <center>Finalizó el flujo actual</center>

                                        {% elif actividad_us.1 %}
                                        <center><a class="btn btn-sm btn-default"
                                                   href="{% url 'proyecto:vista_editarEstadoUS' idP flujo.id actividad_us.0.us.id %}"
                                        >Modificar estado
                                        </a>
                                        </center>
                                            {% endif %}
                                    {% endif %}
                                {% endif %}
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>

                    <br>
                    {% if "editar_flujo" in permisosAsociados and not usActuales%}
                        <a class="btn btn-sm btn-default"
                           href="{% url 'proyecto:vista_editarFlujo' proyecto.id flujo.id %}">Editar nombre del flujo y sus actividades</a>
                    {% endif %}
                <br><br>
                <li><strong>Log de eventos:</strong></li>
                        <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Descripción del evento</th>
                                        <th>Hora y fecha del evento</th>

                                    </tr>
                                </thead>
                                <tbody>
                                {% for log in lista_log %}
                                    <tr>

                                        <td>{{ log.descripcion }}</td>
                                        <td>{{ log.timestamp }}</td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                </div>
            </div>
        </div>

    </div>
{% endblock %}