autenticacion/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
#from django.contrib.auth.views import login,logout
from . import views

app_name = 'autenticacion'
urlpatterns = [
    #url(r'^$',views.vista_index, name="vista_index"),
    url(r'^login/$', views.vista_login, name="vista_login"),
    url(r'^logout/$',views.vista_logout, name="vista_logout"),
]

proyecto/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from proyecto import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'proyecto'


urlpatterns = [
    url(r'^$',views.vista_index, name="vista_index"),
    #PROYECTO
    url(r'^crear_proyecto/$', views.vista_crear_proyecto, name="vista_crear_proyecto"),
    url(r'^(?P<idP>\d+)/consultar_proyecto$', views.vista_consultar_proyecto, name="vista_consultar_proyecto"),
    url(r'^listar_proyectos/$', views.vista_listar_proyectos, name="vista_listar_proyectos"),
    url(r'^(?P<idP>\d+)/modificar_proyecto/$', views.vista_modificar_proyecto, name="vista_modificar_proyecto"),
    url(r'^eliminar_proyecto/$', views.vista_eliminar_proyecto, name="vista_eliminar_proyecto"),
    url(r'^mis_proyectos/$', views.vista_mis_proyectos, name="vista_mis_proyectos"),
    url(r'^(?P<idP>\d+)/agregar_participantes/$', views.vista_agregar_participantes, name="vista_agregar_participantes"),
    url(r'^(?P<idP>\d+)/cancelar_proyecto/$', views.vista_cancelar_proyecto, name="vista_cancelar_proyecto"),
    url(r'^(?P<idP>\d+)/retomar_proyecto/$', views.vista_retomar_proyecto, name="vista_retomar_proyecto"),
    url(r'^(?P<idP>\d+)/finalizar_proyecto/$', views.vista_finalizar_proyecto, name="vista_finalizar_proyecto"),
    url(r'^(?P<idP>\d+)/modificar_SM/$', views.vista_modificar_SM, name="vista_modificar_SM"),

    #USUARIOS
    url(r'^(?P<getIdUsuario>[0-9]+)/ver_usuario/$', views.vista_verUsuario, name="vista_verUsuario"),
    url(r'^lista_usuarios', views.vista_listaUsuarios, name="vista_listaUsuarios"),
    url(r'^(?P<getIdUsuario>[0-9]+)/editar_usuario/$', views.vista_editarUsuario, name="vista_editarUsuario"),
    url(r'^nuevo_usuario/$', views.vista_nuevoUsuario, name="vista_nuevoUsuario"),
    url(r'^eliminar_usuario/$', views.vista_eliminarUsuario, name="vista_eliminarUsuario"),
    url(r'^(?P<getIdUsuario>[0-9]+)/cambiar_contrasenha/$', views.vista_cambiarContrasenha, name="vista_cambiarContrasenha"),

    #PERMISOS
    url(r'^lista_permisos', views.vista_listaPermisos, name="vista_listaPermisos"),
    url(r'^nuevo_permiso/$', views.vista_nuevoPermiso, name="vista_nuevoPermiso"),
    url(r'^(?P<getIdPermiso>[0-9]+)/ver_permiso/$', views.vista_verPermiso, name="vista_verPermiso"),
    url(r'^(?P<getIdPermiso>[0-9]+)/editar_permiso/$', views.vista_editarPermiso, name="vista_editarPermiso"),

    #ROLES
    url(r'^(?P<getIdRol>[0-9]+)/ver_rol/$', views.vista_verRol, name="vista_verRol"),
    url(r'^lista_roles', views.vista_listaRoles, name="vista_listaRoles"),
    url(r'^nuevo_rol/$', views.vista_nuevoRol, name="vista_nuevoRol"),
    url(r'^(?P<getIdRol>[0-9]+)/editar_rol/$', views.vista_editarRol, name="vista_editarRol"),

    #USER STORY
    url(r'^(?P<idP>[0-9]+)/nuevo_us/$', views.vista_crear_userstory, name="vista_crear_userstory"),
    url(r'^eliminar_us/$', views.vista_eliminarUS, name="vista_eliminarUS"),
    url(r'^(?P<idP>[0-9]+)/consultar_us/(?P<idUs>[0-9]+)/$', views.vista_consultar_us, name="vista_consultar_us"),
    url(r'^(?P<idP>[0-9]+)/lista_us/$', views.vista_lista_us, name="vista_lista_us"),
    url(r'^(?P<idP>[0-9]+)/modificar_us/(?P<idUs>[0-9]+)/$', views.vista_modificar_us, name="vista_modificar_us"),
    #url(r'^(?P<idP>[0-9]+)/agregar_developer_us/(?P<idUs>[0-9]+)/$', views.vista_agregar_developer_us, name="vista_agregar_developer_us"), se paso a la parte de Sprint
    url(r'^(?P<idP>[0-9]+)/avance_us/(?P<idUs>[0-9]+)/$', views.vista_registrar_avance_us, name="vista_registrar_avance_us"),
    url(r'^(?P<idP>[0-9]+)/subir_archivo/(?P<idUs>[0-9]+)/$', views.vista_subirArchivo, name="vista_subirArchivo"),
    url(r'^eliminar_archivo/$', views.vista_eliminarArchivo, name="vista_eliminarArchivo"),
    url(r'^eliminar_nota/$', views.vista_eliminarNota, name="vista_eliminarNota"),

    #formularios
    url(r'^eliminar_permiso/$', views.vista_eliminarPermiso, name="vista_eliminarPermiso"),
    url(r'^eliminar_rol/$', views.vista_eliminarRol, name="vista_eliminarRol"),

    #SPRINTS
    url(r'^(?P<idP>[0-9]+)/crear_sprint/$', views.vista_crear_sprint,name="vista_crear_sprint"),
    url(r'^(?P<idP>[0-9]+)/lista_sprint', views.vista_lista_sprint, name="vista_lista_sprint"),
    url(r'^(?P<idP>[0-9]+)/consultar_sprint/(?P<idS>[0-9]+)$', views.vista_consultar_sprint, name="vista_consultar_sprint"),
    url(r'^(?P<idP>[0-9]+)/modificar_sprint/(?P<idS>[0-9]+)$', views.vista_modificar_sprint, name="vista_modificar_sprint"),
    url(r'^eliminar_sprint/$', views.vista_eliminar_sprint, name="vista_eliminar_sprint"),
    url(r'^(?P<idP>[0-9]+)/agregar_us/(?P<idS>[0-9]+)$', views.vista_agregar_us, name="vista_agregar_us"),
    url(r'^(?P<idP>[0-9]+)/agregar_developers_sprint/(?P<idS>[0-9]+)$', views.vista_agregar_developer_sprint, name="vista_agregar_developer_sprint"),
    url(r'^(?P<idP>[0-9]+)/agregar_developer_us/(?P<idS>[0-9]+)/(?P<idUs>[0-9]+)/$', views.vista_agregar_developer_us, name="vista_agregar_developer_us"),
    url(r'^(?P<idP>[0-9]+)/agregar_horas_trabajo_sprint/(?P<idS>[0-9]+)$', views.vista_asignar_horas_trabajo, name="vista_asignar_horas_trabajo"),
    url(r'^(?P<idP>[0-9]+)/ejecutar_sprint/(?P<idS>[0-9]+)$', views.vista_ejecutar_sprint, name="vista_ejecutar_sprint"),
    url(r'^finalizar_sprint/$', views.vista_finalizar_sprint, name="vista_finalizar_sprint"),

    #flujos
    url(r'^(?P<idP>[0-9]+)/lista_flujos', views.vista_listaFlujos, name="vista_listaFlujos"),
    url(r'^(?P<idP>[0-9]+)/nuevo_flujo/$', views.vista_nuevoFlujo, name="vista_nuevoFlujo"),
    url(r'^ver_flujo/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_verFlujo, name="vista_verFlujo"),
    url(r'^editar_flujo/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_editarFlujo, name="vista_editarFlujo"),
    url(r'^editar_estadoUS/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/(?P<idUs>[0-9]+)/$', views.vista_editarEstadoUS, name="vista_editarEstadoUS"),
    url(r'^editar_actividad/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/(?P<idActividad>[0-9]+)/$', views.vista_editarActividad,name="vista_editarActividad"),
    url(r'^agregar_us_a_flujo/(?P<idP>[0-9]+)/(?P<idUS>[0-9]+)/(?P<idS>[0-9]+)$', views.vista_agregarUSaFlujo,name="vista_agregarUSaFlujo"),

    #kanban
    url(r'^lista_kanban/(?P<idP>[0-9]+)/$', views.vista_listaKanban, name="vista_listaKanban"),
    url(r'^ver_kanban/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_verKanban, name="vista_verKanban"),
]

sgp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("autenticacion.urls", namespace='autenticacion')),
    url(r'^', include("proyecto.urls", namespace='proyecto')),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SGP-{% block titulo %}
    <link rel="icon" class="glyphicon glyphicon-heart" />

    {% endblock %} </title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic&amp;subset=latin,latin-ext,cyrillic' rel='stylesheet' type='text/css'>
    <!-- Custom CSS -->
    <link href="{% static 'css/sb-admin.css'%}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'css/plugins/morris.css'%}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'js/plugins/morris/raphael.min.js' %}"></script>
    <script src="{% static 'js/plugins/morris/morris.min.js' %}"></script>
    <script src="{% static 'js/plugins/morris/morris-data.js' %}"></script>
    <script src="{% static 'js/bootbox.js'  %}"></script>



    <script src="{% static 'js/jquery-1.7.2.min.js'  %}"></script>
    <script src="{% static 'js/jquery.noty.packaged.js'  %}"></script>
    <script src="{% static 'js/notification_html.js' %}"></script>


    <script>

            function generate(type, text) {

                var n = noty({
                    text: text,
                    type: type,
                    dismissQueue: true,
                    layout: 'bottomRight',
                    closeWith: ['click'],
                    theme: 'relax',
                    maxVisible: 10,
                    animation: {
                        open: 'animated bounceInRight',
                        close: 'animated bounceOutRight',
                        easing: 'swing',
                        speed: 500
                    }
                });
                console.log('html: ' + n.options.id);

                setTimeout(function () {
                            $.noty.closeAll();
                        }, 3000);
            }

    </script>

{% block header %}

{% endblock %}
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">SGP</a>
            </div>
            <!-- Top Menu Items -->
           {% include 'topMenu.html' %}
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                {% include 'sidebarMenu.html' %}
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                {% block contenido %}

                {% endblock %}
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->


</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block titulo %}
    Inicio
{% endblock %}
{% block header %}
{% endblock %}
{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Sistema Gerenciador de Proyectos
                <small></small>
            </h1>

        </div>
    </div>

    <!-- /.row -->

    <div class="row">
        <div class="col-lg-12">

        </div>
        {% if user.is_staff %}
            <div class="col-lg-3 col-md-6 col-md-offset-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-calendar fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ cantProyectos }}</div>
                                <div>Proyectos</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'proyecto:vista_listar_proyectos' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver lista de Proyectos</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-md-offset-0">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-users fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ cantUsuarios }}</div>
                                <div>Usuarios</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'proyecto:vista_listaUsuarios' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver lista de usuarios</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
        {% else %}
            <div class="col-lg-4 col-md-6 col-md-offset-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-calendar fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ cantProyectos }}</div>
                                <div>Proyectos</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'proyecto:vista_mis_proyectos' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver Mis Proyectos</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
    <!-- /.row  -->
    <div class="row">

            <div class="col-lg-6 col-md-3 col-md-offset-3">
                <div class="panel panel-yellow">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-calendar-o fa-5x"></i>
                            </div>
                            <div class=" text-center">
                                <div><h2>Calendario</h2></div>
                            </div>
                        </div>
                    </div>
                    <a href="#">
                        <div class="panel-footer">

                            <iframe src="https://calendar.google.com/calendar/embed?showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;height=400&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=ck6ednfept5vkviunhucp41de8%40group.calendar.google.com&amp;color=%235F6B02&amp;ctz=America%2FAsuncion"
                                    style="border-width:0; " width="100%" height="100%" frameborder="0"
                                    scrolling="no"></iframe>

                        </div>
                    </a>
                </div>
            </div>


    </div>

    <!-- /.row  -->
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i>Últimas actividades en User
                        Stories</h3>
                </div>
                <div class="panel-body">
                    <div class="list-group">
                        {% for log in logUs %}
                            <a href="#" class="list-group-item">
                                <span class="badge">{{ log.timestamp }}</span>
                                <i class="fa fa-fw fa-check"></i> <b>En
                                '{{ log.us.descripcion_corta }}': </b>{{ log.descripcion }}
                            </a>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i>Últimas actividades en Sprints
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="list-group">
                        {% for log in logSprint %}
                            <a href="#" class="list-group-item">
                                <span class="badge">{{ log.timestamp }}</span>
                                <i class="fa fa-fw fa-check"></i> <b>En
                                Sprint '{{ log.sprint.id }}': </b>{{ log.descripcion }}
                            </a>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i>Últimas actividades en Flujos
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="list-group">
                        {% for log in logFlujos %}
                            <a href="#" class="list-group-item">
                                <span class="badge">{{ log.timestamp }}</span>
                                <i class="fa fa-fw fa-check"></i> <b>En
                                '{{ log.flujo.descripcion }}': </b>{{ log.descripcion }}
                            </a>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- /.row  -->
{% endblock %}

templates/sidebarMenu.html
{% load staticfiles %}

<div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="{% url 'proyecto:vista_index' %}"><i class="fa fa-fw fa-home"></i> Dashboard</a>
                    </li>

                    {% if request.user.is_staff %}

                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#proyecto"><i class="fa fa-fw fa-calendar"></i>Proyectos <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="proyecto" class="collapse">
                            <li>
                                <a href= "{% url 'proyecto:vista_crear_proyecto' %}">Crear Proyecto</a>
                            </li>
                            <li>
                                <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de Proyectos</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#usuarios"><i class="fa fa-fw fa-users"></i> Usuarios <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="usuarios" class="collapse">
                            <li>
                                <a href="{% url 'proyecto:vista_listaUsuarios' %}">Lista de Usuarios</a>
                            </li>
                            <li>
                                <a href="{% url 'proyecto:vista_listaPermisos' %}">Lista de Permisos</a>
                            </li>
                            <li>
                                <a href="{% url 'proyecto:vista_listaRoles' %}">Lista de Roles</a>
                            </li>
                        </ul>
                    </li>



                    {% else%}
                                <li>
                                    <a href="{% url 'proyecto:vista_mis_proyectos' %}"><i class="fa fa-fw fa-list-alt"></i> Mis Proyectos</a>
                                </li>
                    {% endif %}
                </ul>
            </div>

templates/sidebarMenu_para_proyecto.html
{% load staticfiles %}

<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li class="active">
            <a href="{% url 'proyecto:vista_index' %}"><i class="fa fa-fw fa-home"></i> Dashboard</a>
        </li>
        {% if not request.user.is_staff %}
            <li>
                <a href="{% url 'proyecto:vista_mis_proyectos' %}"><i class="fa fa-fw fa-list-alt"></i> Mis Proyectos</a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'proyecto:vista_listar_proyectos' %}"><i class="fa fa-fw fa-desktop"></i> Lista de Proyectos</a>
            </li>
        {% endif %}
        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#proyecto"><i class="fa fa-fw fa-calendar"></i>Proyecto <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="proyecto" class="collapse">
                <li>
                    <a href= "{% url 'proyecto:vista_consultar_proyecto' idP %}">Detalles</a>
                </li>
                {% if 'modificar_proyecto' in permisosAsociados or request.user.is_staff %}
                    <li>
                        <a href= "{% url 'proyecto:vista_modificar_proyecto' idP %}">Modificar</a>
                    </li>
                {% endif %}
                {% if 'modificar_SM' in permisosAsociados %}
                    <li>
                        <a href= "{% url 'proyecto:vista_modificar_SM' idP %}">Reasignar SM</a>
                    </li>
                {% endif %}
                {% if proyecto.estado == 'EP' %}
                    {% if 'agregar_participantes' in permisosAsociados %}
                        <li>
                            <a href="{% url 'proyecto:vista_agregar_participantes' idP %}">Iniciar</a>
                        </li>
                    {% endif %}
                {% else %}
                    {% if 'agregar_participantes' in permisosAsociados %}
                        <li>
                            <a href="{% url 'proyecto:vista_agregar_participantes' idP %}">Participantes</a>
                        </li>
                    {% endif %}
                {% endif %}

                {% if proyecto.estado == 'IN' and 'cancelar_proyecto' in permisosAsociados %}
                    <li>
                        <a href= "{% url 'proyecto:vista_cancelar_proyecto' idP %}">Cancelar</a>
                    </li>
                {% endif %}
                {% if proyecto.estado == 'CA' and 'modificar_proyecto' in permisosAsociados %}
                    <li>
                        <a href= "{% url 'proyecto:vista_retomar_proyecto' idP %}">Retomar</a>
                    </li>
                {% endif %}
                {% if proyecto.estado == 'IN' and proyecto.puede_finalizar and 'finalizar_proyecto' in permisosAsociados %}
                    <li>
                        <a href= "{% url 'proyecto:vista_finalizar_proyecto' idP %}">Finalizar</a>
                    </li>
                {% endif %}
            </ul>
        </li>
        {% if proyecto.get_estado == 'IN' %}
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#us"><i class="fa fa-fw fa-pencil-square-o"></i> User Story <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="us" class="collapse">
                    {% if 'crear_us' in permisosAsociados %}
                        <li>
                            <a href="{% url 'proyecto:vista_crear_userstory' idP %}">Crear</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'proyecto:vista_lista_us' idP %}">Product Backlog</a>
                    </li>
                </ul>
            </li>

            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#sprint"><i class="fa fa-fw fa-tasks"></i> Sprint <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="sprint" class="collapse">
                    {% if 'crear_sprint' in permisosAsociados %}
                        <li>
                            <a href="{% url 'proyecto:vista_crear_sprint' idP %}">Crear</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'proyecto:vista_lista_sprint' idP %}">Backlog</a>
                    </li>

                </ul>
            </li>

            <li>
                <a href="{% url 'proyecto:vista_listaKanban' idP%}"><i class="fa fa-fw fa-columns"></i> Kanban</a>
            </li>
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#flujo"><i class="fa fa-fw fa-arrow-right"></i> Flujo <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="flujo" class="collapse">
                    {% if 'crear_flujo' in permisosAsociados %}
                        <li>
                            <a href="{% url 'proyecto:vista_nuevoFlujo' proyecto.id%}">Crear Flujo</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'proyecto:vista_listaFlujos' proyecto.id%}">Lista de Flujos</a>
                    </li>

                </ul>
            </li>


        {% endif %}
        {% if request.user.is_staff %}
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#usuarios"><i class="fa fa-fw fa-wrench"></i> Usuarios <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="usuarios" class="collapse">
                    <li>
                        <a href="{% url 'proyecto:vista_listaUsuarios' %}">Lista de Usuarios</a>
                    </li>
                    <li>
                        <a href="{% url 'proyecto:vista_listaPermisos' %}">Lista de Permisos</a>
                    </li>
                    <li>
                        <a href="{% url 'proyecto:vista_listaRoles' %}">Lista de Roles</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
</div>

templates/topMenu.html
 <ul class="nav navbar-right top-nav">


                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ request.user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'proyecto:vista_verUsuario'  request.user.id%}"><i class="fa fa-fw fa-user"></i> Perfil</a>
                        </li>

                        <li class="divider"></li>
                        <li>
                            <a href="{% url 'autenticacion:vista_logout' %}"><i class="fa fa-fw fa-power-off"></i>Cerrar sesión</a>
                        </li>
                    </ul>
                </li>
            </ul>