proyecto/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from proyecto import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'proyecto'


urlpatterns = [
    url(r'^$',views.vista_index, name="vista_index"),
    #PROYECTO
    url(r'^crear_proyecto/$', views.vista_crear_proyecto, name="vista_crear_proyecto"),
    url(r'^(?P<idP>\d+)/consultar_proyecto$', views.vista_consultar_proyecto, name="vista_consultar_proyecto"),
    url(r'^listar_proyectos/$', views.vista_listar_proyectos, name="vista_listar_proyectos"),
    url(r'^(?P<idP>\d+)/modificar_proyecto/$', views.vista_modificar_proyecto, name="vista_modificar_proyecto"),
    url(r'^eliminar_proyecto/$', views.vista_eliminar_proyecto, name="vista_eliminar_proyecto"),
    url(r'^mis_proyectos/$', views.vista_mis_proyectos, name="vista_mis_proyectos"),
    url(r'^(?P<idP>\d+)/agregar_participantes/$', views.vista_agregar_participantes, name="vista_agregar_participantes"),
    url(r'^(?P<idP>\d+)/cancelar_proyecto/$', views.vista_cancelar_proyecto, name="vista_cancelar_proyecto"),
    url(r'^(?P<idP>\d+)/retomar_proyecto/$', views.vista_retomar_proyecto, name="vista_retomar_proyecto"),
    url(r'^(?P<idP>\d+)/finalizar_proyecto/$', views.vista_finalizar_proyecto, name="vista_finalizar_proyecto"),
    url(r'^(?P<idP>\d+)/modificar_SM/$', views.vista_modificar_SM, name="vista_modificar_SM"),

    #USUARIOS
    url(r'^(?P<getIdUsuario>[0-9]+)/ver_usuario/$', views.vista_verUsuario, name="vista_verUsuario"),
    url(r'^lista_usuarios', views.vista_listaUsuarios, name="vista_listaUsuarios"),
    url(r'^(?P<getIdUsuario>[0-9]+)/editar_usuario/$', views.vista_editarUsuario, name="vista_editarUsuario"),
    url(r'^nuevo_usuario/$', views.vista_nuevoUsuario, name="vista_nuevoUsuario"),
    url(r'^eliminar_usuario/$', views.vista_eliminarUsuario, name="vista_eliminarUsuario"),
    url(r'^(?P<getIdUsuario>[0-9]+)/cambiar_contrasenha/$', views.vista_cambiarContrasenha, name="vista_cambiarContrasenha"),

    #PERMISOS
    url(r'^lista_permisos', views.vista_listaPermisos, name="vista_listaPermisos"),
    url(r'^nuevo_permiso/$', views.vista_nuevoPermiso, name="vista_nuevoPermiso"),
    url(r'^(?P<getIdPermiso>[0-9]+)/ver_permiso/$', views.vista_verPermiso, name="vista_verPermiso"),
    url(r'^(?P<getIdPermiso>[0-9]+)/editar_permiso/$', views.vista_editarPermiso, name="vista_editarPermiso"),

    #ROLES
    url(r'^(?P<getIdRol>[0-9]+)/ver_rol/$', views.vista_verRol, name="vista_verRol"),
    url(r'^lista_roles', views.vista_listaRoles, name="vista_listaRoles"),
    url(r'^nuevo_rol/$', views.vista_nuevoRol, name="vista_nuevoRol"),
    url(r'^(?P<getIdRol>[0-9]+)/editar_rol/$', views.vista_editarRol, name="vista_editarRol"),

    #USER STORY
    url(r'^(?P<idP>[0-9]+)/nuevo_us/$', views.vista_crear_userstory, name="vista_crear_userstory"),
    url(r'^eliminar_us/$', views.vista_eliminarUS, name="vista_eliminarUS"),
    url(r'^(?P<idP>[0-9]+)/consultar_us/(?P<idUs>[0-9]+)/$', views.vista_consultar_us, name="vista_consultar_us"),
    url(r'^(?P<idP>[0-9]+)/lista_us/$', views.vista_lista_us, name="vista_lista_us"),
    url(r'^(?P<idP>[0-9]+)/modificar_us/(?P<idUs>[0-9]+)/$', views.vista_modificar_us, name="vista_modificar_us"),
    #url(r'^(?P<idP>[0-9]+)/agregar_developer_us/(?P<idUs>[0-9]+)/$', views.vista_agregar_developer_us, name="vista_agregar_developer_us"), se paso a la parte de Sprint
    url(r'^(?P<idP>[0-9]+)/avance_us/(?P<idUs>[0-9]+)/$', views.vista_registrar_avance_us, name="vista_registrar_avance_us"),
    url(r'^(?P<idP>[0-9]+)/subir_archivo/(?P<idUs>[0-9]+)/$', views.vista_subirArchivo, name="vista_subirArchivo"),
    url(r'^eliminar_archivo/$', views.vista_eliminarArchivo, name="vista_eliminarArchivo"),
    url(r'^eliminar_nota/$', views.vista_eliminarNota, name="vista_eliminarNota"),

    #formularios
    url(r'^eliminar_permiso/$', views.vista_eliminarPermiso, name="vista_eliminarPermiso"),
    url(r'^eliminar_rol/$', views.vista_eliminarRol, name="vista_eliminarRol"),

    #SPRINTS
    url(r'^(?P<idP>[0-9]+)/crear_sprint/$', views.vista_crear_sprint,name="vista_crear_sprint"),
    url(r'^(?P<idP>[0-9]+)/lista_sprint', views.vista_lista_sprint, name="vista_lista_sprint"),
    url(r'^(?P<idP>[0-9]+)/consultar_sprint/(?P<idS>[0-9]+)$', views.vista_consultar_sprint, name="vista_consultar_sprint"),
    url(r'^(?P<idP>[0-9]+)/modificar_sprint/(?P<idS>[0-9]+)$', views.vista_modificar_sprint, name="vista_modificar_sprint"),
    url(r'^eliminar_sprint/$', views.vista_eliminar_sprint, name="vista_eliminar_sprint"),
    url(r'^(?P<idP>[0-9]+)/agregar_us/(?P<idS>[0-9]+)$', views.vista_agregar_us, name="vista_agregar_us"),
    url(r'^(?P<idP>[0-9]+)/agregar_developers_sprint/(?P<idS>[0-9]+)$', views.vista_agregar_developer_sprint, name="vista_agregar_developer_sprint"),
    url(r'^(?P<idP>[0-9]+)/agregar_developer_us/(?P<idS>[0-9]+)/(?P<idUs>[0-9]+)/$', views.vista_agregar_developer_us, name="vista_agregar_developer_us"),
    url(r'^(?P<idP>[0-9]+)/agregar_horas_trabajo_sprint/(?P<idS>[0-9]+)$', views.vista_asignar_horas_trabajo, name="vista_asignar_horas_trabajo"),
    url(r'^(?P<idP>[0-9]+)/ejecutar_sprint/(?P<idS>[0-9]+)$', views.vista_ejecutar_sprint, name="vista_ejecutar_sprint"),
    url(r'^finalizar_sprint/$', views.vista_finalizar_sprint, name="vista_finalizar_sprint"),

    #flujos
    url(r'^(?P<idP>[0-9]+)/lista_flujos', views.vista_listaFlujos, name="vista_listaFlujos"),
    url(r'^(?P<idP>[0-9]+)/nuevo_flujo/$', views.vista_nuevoFlujo, name="vista_nuevoFlujo"),
    url(r'^ver_flujo/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_verFlujo, name="vista_verFlujo"),
    url(r'^editar_flujo/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_editarFlujo, name="vista_editarFlujo"),
    url(r'^editar_estadoUS/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/(?P<idUs>[0-9]+)/$', views.vista_editarEstadoUS, name="vista_editarEstadoUS"),
    url(r'^editar_actividad/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/(?P<idActividad>[0-9]+)/$', views.vista_editarActividad,name="vista_editarActividad"),
    url(r'^agregar_us_a_flujo/(?P<idP>[0-9]+)/(?P<idUS>[0-9]+)/(?P<idS>[0-9]+)$', views.vista_agregarUSaFlujo,name="vista_agregarUSaFlujo"),

    #kanban
    url(r'^lista_kanban/(?P<idP>[0-9]+)/$', views.vista_listaKanban, name="vista_listaKanban"),
    url(r'^ver_kanban/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_verKanban, name="vista_verKanban"),
]

sgp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("autenticacion.urls", namespace='autenticacion')),
    url(r'^', include("proyecto.urls", namespace='proyecto')),
]

proyecto/views/sprint_views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.shortcuts import render
from proyecto.forms import *
from proyecto.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import redirect
import datetime


@login_required
@csrf_protect
def vista_crear_sprint(request,idP):
    """
    Esta funcion vista permite crear un nuevo Sprint asociado a un proyecto
    @param request: parametro recibido por defecto por las vistas de Django.
    @param idP: Identificador unico del proyecto
    @return: Se renderiza un template con formularios para la creacion de Sprints
    """
    msj_error = ''
    #Solo se permite el acceso a las personas que tienen asociados a sus roles crear sprints
    proyecto = Proyecto.objects.get(id=idP)
    usuario= Usuario.objects.get(user=request.user)
    if not usuario.tienePermiso(proyecto,'crear_sprint'):
        return HttpResponseRedirect('/')

    if request.method=='POST':
        form = FormCrearSprint(request.POST)
        if form.is_valid():
            datos = form.cleaned_data
            sprint = Sprint()
            sprint.duracion_dias = datos['duracion_dias_form']
            sprint.estado = 'PN'
            sprint.save()
            #Se relaciona sprint con proyecto en la tabla intermedia
            psu = Proyecto_Sprint_Us.objects.create(proyecto=proyecto,sprint=sprint)
            #Se relaciona sprint con developer en la tabla intermedia
            psu = Sprint_Developers.objects.create(proyecto=proyecto,sprint=sprint)
            psu.save()
            #Registrar en el log
            Log_Sprint.objects.create(sprint=sprint,descripcion="Se ha creado el sprint.")
            # Mensaje de que se ha creado un US con exito
            messages.success(request,"Se creo exitosamente el Sprint")
            return HttpResponseRedirect(reverse('proyecto:vista_lista_sprint', args=[idP]))
        else:
            msj_error = 'Ten en cuenta las indicaciones sobre los campos'
    else:
        # Si no se cargaron los datos se devuelve un formulario vacio
        form = FormCrearUserStory

    #obtener permisos de un usuario
    usuario = Usuario.objects.get(user=request.user)
    idPermisos= usuario.getListaPermisos(proyecto).values_list('permiso_id',flat=True)
    permisosAsociados=Permiso.objects.filter(id__in = idPermisos).values_list('nombre',flat=True)

    context = {
        'form':form,
        'proyecto':proyecto,
        'idP':idP,
        'msj_error':msj_error,
        'permisosAsociados':permisosAsociados,
    }

    return render(request,"html/sprints/crear_sprint.html",context)

@login_required
def vista_lista_sprint(request,idP):
    """
    La funcion vista "Lista Sprints" presenta un listado de todos los sprints registrados
    @param request: Parametro por defecto que recibe una vista de Django.
    @param idP: Identificador unico del Proyecto
    @return: Renderiza el html correspondiente, el cual recibe por contexto la lista de sprints
    """

    #Solo se permite el acceso a las personas que tienen asociados a sus roles crear sprints
    proyecto = Proyecto.objects.get(id=idP)
    usuario= Usuario.objects.get(user=request.user)
    if not usuario.tienePermiso(proyecto,'listar_sprint'):
        return HttpResponseRedirect('/')

    #Lista de Sprints asociadas al proyecto
    lista_sprints = Proyecto_Sprint_Us.objects.filter(proyecto=proyecto).all().distinct('sprint_id')
    listaSprints=[]
    for i in lista_sprints:
        listaSprints.append([i,i.sprint.puedeEjecutarse(proyecto)])

    #Bandera para saber si hay varios en ejecución
    sprint_en_ejecucion = False
    for s in lista_sprints:
        if s.sprint.estado == 'EJ':
            sprint_en_ejecucion = True

    #obtener permisos de un usuario
    usuario = Usuario.objects.get(user=request.user)
    idPermisos= usuario.getListaPermisos(proyecto).values_list('permiso_id',flat=True)
    permisosAsociados=Permiso.objects.filter(id__in = idPermisos).values_list('nombre',flat=True)
    #if not (usuario.tienePermiso(proyecto, 'agregar_participantes') and
                #usuario.tienePermiso(proyecto, 'crear_us')):


    context = {
        'lista_sprints': lista_sprints,
        'listaSprints':listaSprints,
        'idP':idP,
        'proyecto':proyecto,
        'permisosAsociados':permisosAsociados,
        'sprint_en_ejecucion':sprint_en_ejecucion,
    }
    return render(request, "html/sprints/lista_sprint.html", context)

@login_required
def vista_consultar_sprint(request, idP, idS):
    """
    La funcion "Consultar Sprint" nos permite ver los detalles de un Sprint especifico.
    @param request:parametro por defecto que recibe una vista de Django
    @param idP: Identificador unico del Proyecto
    @param idS: Identificador unico del Sprint asociado al proyecto
    @return: se renderiza un template que muestra los detalles de un Sprint
    """
    #Solo se permite el acceso a los usuarios que tienen asociados el permiso de "Listar Sprints"
    proyecto = Proyecto.objects.get(id=idP)
    usuario= Usuario.objects.get(user=request.user)
    if not usuario.tienePermiso(proyecto,'ver_sprint'):
        return HttpResponseRedirect('/')

    sprint = get_object_or_404(Sprint,id=idS)
    #Lista de User Stories del Sprint
    try:
        lista_us = Proyecto_Sprint_Us.objects.filter(proyecto=proyecto,sprint=sprint).all().order_by('-us__valor_prioridad')
        #obtener los us asignados a flujos
        listaIdUsEstanEnFlujo=Flujo_Us.objects.all().values_list('us_id',flat=True)
    except Proyecto_Sprint_Us.DoesNotExist, Flujo_Us.DoesNotExist:
        lista_us = None
        listaIdUsEstanEnFlujo = None

    #Se crea un diccionario con todos los US del Sprint para instanciar los autores de los US
    dicc_US_dev = {}
    for x in lista_us:
        if x.us != None:
            us = UserStory.objects.get(id=x.us.id)
            pb = Product_Backlog.objects.get(proyecto=proyecto,us=us)
            dicc_US_dev[x.us.id] = pb.usuario

    #Se crea un diccionario con todos los US del Sprint para instanciar los flujos de los US
    dicc_US_flujos = {}
    for x in lista_us:
        if x.us != None:
            us = UserStory.objects.get(id=x.us.id)
            try:
                fus = Flujo_Us.objects.get(us=us)
            except Flujo_Us.DoesNotExist:
                fus = None
            if fus != None:
                dicc_US_flujos[x.us.id] = fus.flujo.descripcion
            else:
                dicc_US_flujos[x.us.id] = "None"


    #Lista de developers asociados al proyecto
    try:
        lista_developers_sin_repetir = Sprint_Developers.objects.filter(proyecto=proyecto,sprint=sprint).all()
    except Sprint_Developers:
        lista_developers_sin_repetir = None

    #Lista developers True o False, de acuerdo si existen o no Developers en el sprint
    ld_vacia = True
    for y in lista_developers_sin_repetir:
        if y.usuario != None:
            ld_vacia = False

    #Capacidad del Sprint
    capacidad = 0
    for x in lista_developers_sin_repetir:
        capacidad = x.hs_trabajo_usuario*sprint.duracion_dias + capacidad
    sprint.capacidad_horas = capacidad
    sprint.save()

    #Avance del Sprint
    avance_sprint = 0.0
    total_hs_us = 0
    for x in lista_us:
        if not x.us == None:
            avance_sprint = avance_sprint + int(x.us.tiempo_dedicado)
            total_hs_us = x.us.tiempo_estimado + total_hs_us
    sprint.avance_horas = avance_sprint
    #Horas estimadas para terminar Sprint
    sprint.horas_para_terminar = total_hs_us - sprint.avance_horas
    sprint.save()

    #Saldo Sprint
    horas_US = 0
    saldo = sprint.capacidad_horas - total_hs_us

    #obtener permisos de un usuario
    usuario = Usuario.objects.get(user=request.user)
    idPermisos= usuario.getListaPermisos(proyecto).values_list('permiso_id',flat=True)
    permisosAsociados=Permiso.objects.filter(id__in = idPermisos).values_list('nombre',flat=True)

    #controlar las condiciones para ejecutarse el sprint
    condicionesEjecucion= sprint.getCondicionesParaEjecutarse(proyecto)
    mensaje = []
    if not condicionesEjecucion.get('puedeEjecutarse'):

        mensaje.append("Este sprint aún no puede ejecutarse porque:")
        if not condicionesEjecucion.get('hayUS'):
            mensaje.append(" ** No hay User Stories asignados a este sprint.")
        if not condicionesEjecucion.get('todosUStienenFlujo'):
            mensaje.append("** No todos los User Stories de este sprint estan asignados a algun flujo.")
        if not condicionesEjecucion.get('todoUStieneDeveloper'):
            mensaje.append("** No todos los User Stories tienen asignados un developer.")
        if not condicionesEjecucion.get('cadaDeveloperTieneHorasAsignadas'):
            mensaje.append("** No todos los developers de este sprint tienen horas de trabajo asignadas.")

    if total_hs_us > sprint.capacidad_horas:
        mensaje.append("OBS: La capacidad del Sprint es inferior al tiempo estimado para realizar los US del Sprint")

    lista_log=Log_Sprint.objects.order_by('id').filter(sprint=sprint)

    context = {
        'proyecto':proyecto,
        'sprint':sprint,
        'idP':idP,
        'idS':idS,
        'permisosAsociados':permisosAsociados,
        'lista_us':lista_us,
        'lista_developers_sin_repetir':lista_developers_sin_repetir,
        'mensaje':mensaje,
        'ld_vacia':ld_vacia,
        'listaIdUsEstanEnFlujo':listaIdUsEstanEnFlujo,
        'lista_log':lista_log,
        'dicc_US_dev':dicc_US_dev,
        'dicc_US_flujos':dicc_US_flujos,
        'saldo':saldo,
        'total_hs_us':total_hs_us,
    }

templates/html/sprints/agregar_us.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    Agregar US a Sprint
{% endblock %}
{% block header %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <script> generate("success","{{ message }}") </script>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Agregar User Story a Sprint
                <small></small>
            </h1>

            <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                            </li>
                            {% if request.user.is_staff %}
                             <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de Proyectos</a>
                            </li>
                            {% else %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_mis_proyectos' %}">Mis Proyectos</a>
                            </li>
                            {% endif %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_proyecto' proyecto.id %}">Consulta Proyecto</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_lista_sprint' idP %}">Sprint Backlog</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_sprint' idP idS %}">Consulta de Sprint</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-list"></i> Agregar User Story a Sprint
                            </li>
            </ol>
        </div>
        <div class="col-lg-9">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="form-group">
                    <ul>
                        <li><strong>Duración del Sprint en días:</strong> {{ sprint.duracion_dias }} </li><br>
                        <li><strong>Saldo del Sprint en horas:</strong> {{ saldo }} </li><br>

                        <li><strong>Elegir User Stories para agregar al Sprint: </strong></li>
                    </ul>
                           {% for us in us_actuales %}
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id = "us_form" name="us_form" value="{{ us.id }}" checked>Descripción corta:&nbsp;{{ us.descripcion_corta }}&nbsp;|&nbsp;Horas estimadas:&nbsp;{{ us.tiempo_estimado }}|&nbsp;Prioridad:&nbsp;{{ us.get_prioridad_verbose }}<br>
                                </label>
                            </div>
                            {% endfor %}
                            {% for us in us_sin_asingar %}
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id = "us_form" name="us_form" value="{{ us.id }}">Descripción corta:&nbsp;{{ us.descripcion_corta }}&nbsp;|&nbsp;Horas estimadas:&nbsp;{{ us.tiempo_estimado }}|&nbsp;Prioridad:&nbsp;{{ us.get_prioridad_verbose }}<br>
                                </label>
                            </div>
                            {% endfor %}
                    </div>
                    <br>
                    <button type="submit" class="btn btn-success">Guardar</button>
                    <button type="reset" class="btn btn-default">Limpiar datos</button>
                    <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_consultar_sprint' idP idS%}">Cancelar</a>
                </form>
        </div>
    </div>

{% endblock %}

templates/html/sprints/lista_sprint.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    Sprint Backlog
{% endblock %}
{% block header %}
    <script>
        function eliminarSprint(idS) {

            bootbox.dialog({
                message: "¿Realmente desea eliminar el Sprint '"+idS+"'?",
                title: "Eliminar Sprint",
                buttons: {
                    success: {
                        label: "Sí",
                        className: "btn-success",
                        callback: function () {

                            var request = $.ajax({
                                type: "POST",
                                url: "{% url 'proyecto:vista_eliminar_sprint' %}",
                                data: {
                                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                                    "idP": {{ proyecto.id }},
                                    "idS": idS
                                },
                            });
                            request.done(function (response) {
                                    alert("Sprint eliminado..");
                                window.location="{% url 'proyecto:vista_lista_sprint' proyecto.id %}"
                            });
                        }
                    },
                    danger: {
                        label: "No",
                        className: "btn-danger"
                    }
                }
            });
        }

        function finalizarSprint(idS) {

            bootbox.dialog({
                message: "¿Realmente desea finalizar el Sprint '"+idS+"'?",
                title: "Finalizar Sprint",
                buttons: {
                    success: {
                        label: "Sí",
                        className: "btn-success",
                        callback: function () {

                            var request = $.ajax({
                                type: "POST",
                                url: "{% url 'proyecto:vista_finalizar_sprint' %}",
                                data: {
                                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                                    "idP": {{ proyecto.id }},
                                    "idS": idS
                                },
                            });
                            request.done(function (response) {
                                alert("Sprint finalizado");
                                window.location="{% url 'proyecto:vista_lista_sprint' proyecto.id %}"
                            });
                        }
                    },
                    danger: {
                        label: "No",
                        className: "btn-danger"
                    }
                }
            });
        }

    </script>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <script> generate("success","{{ message }}") </script>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}
{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Sprint Backlog
                <small></small>
            </h1>

            <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                            </li>
                            {% if request.user.is_staff %}
                             <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de Proyectos</a>
                            </li>
                            {% else %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_mis_proyectos' %}">Mis Proyectos</a>
                            </li>
                            {% endif %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_proyecto' proyecto.id %}">Consulta Proyecto</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-list"></i> Sprint Backlog
                            </li>
            </ol>
        </div>
        <div class="col-lg-9">
            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th><center>Duración del Sprint</center></th>
                                        <th><center>Estado del Sprint</center></th>
                                        <th><center>Sprint</center></th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for elemento in listaSprints %}
                                    <tr>
                                        <td>{{ elemento.0.sprint.duracion_dias }}</td>
                                        <td>{{ elemento.0.sprint.get_estado_verbose }}</td>
                                        <td>
                                            <center>
                                                {% if 'ejecutar_sprint' in permisosAsociados and elemento.0.sprint.estado == 'PN' and sprint_en_ejecucion == False and elemento.1%}
                                                    <a class="btn btn-sm btn-success" href="{% url 'proyecto:vista_ejecutar_sprint' proyecto.id elemento.0.sprint.id  %}">Iniciar</a>
                                                {% endif %}
                                                <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_consultar_sprint' proyecto.id elemento.0.sprint.id %}">Detalles</a>
                                                {% if elemento.0.sprint.estado != 'FI' %}
                                                    {% if 'editar_sprint' in permisosAsociados %}
                                                        <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_modificar_sprint' proyecto.id elemento.0.sprint.id %}">Modificar</a>
                                                        <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_agregar_developer_sprint' proyecto.id elemento.0.sprint.id %}">Developers</a>
                                                    {% endif %}
                                                {% endif %}
                                                {% if 'finalizar_sprint' in permisosAsociados and elemento.0.sprint.estado == 'EJ' %}
                                                    <a href="javascript:finalizarSprint({{elemento.0.sprint.id}});" class="btn btn-sm btn-danger">Finalizar</a>
                                                {% endif %}
                                                <!--
                                                 if 'eliminar_sprint' in permisosAsociados %}
                                                    <a href="javascript:eliminarSprint({{elemento.sprint.id}});" class="btn btn-sm btn-danger">Eliminar</a>
                                                endif %}
                                                -->
                                            </center>
                                        </td>
                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
        </div>

    </div>

{% endblock %}