proyecto/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from proyecto import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'proyecto'


urlpatterns = [
    url(r'^$',views.vista_index, name="vista_index"),
    #PROYECTO
    url(r'^crear_proyecto/$', views.vista_crear_proyecto, name="vista_crear_proyecto"),
    url(r'^(?P<idP>\d+)/consultar_proyecto$', views.vista_consultar_proyecto, name="vista_consultar_proyecto"),
    url(r'^listar_proyectos/$', views.vista_listar_proyectos, name="vista_listar_proyectos"),
    url(r'^(?P<idP>\d+)/modificar_proyecto/$', views.vista_modificar_proyecto, name="vista_modificar_proyecto"),
    url(r'^eliminar_proyecto/$', views.vista_eliminar_proyecto, name="vista_eliminar_proyecto"),
    url(r'^mis_proyectos/$', views.vista_mis_proyectos, name="vista_mis_proyectos"),
    url(r'^(?P<idP>\d+)/agregar_participantes/$', views.vista_agregar_participantes, name="vista_agregar_participantes"),
    url(r'^(?P<idP>\d+)/cancelar_proyecto/$', views.vista_cancelar_proyecto, name="vista_cancelar_proyecto"),
    url(r'^(?P<idP>\d+)/retomar_proyecto/$', views.vista_retomar_proyecto, name="vista_retomar_proyecto"),
    url(r'^(?P<idP>\d+)/finalizar_proyecto/$', views.vista_finalizar_proyecto, name="vista_finalizar_proyecto"),
    url(r'^(?P<idP>\d+)/modificar_SM/$', views.vista_modificar_SM, name="vista_modificar_SM"),

    #USUARIOS
    url(r'^(?P<getIdUsuario>[0-9]+)/ver_usuario/$', views.vista_verUsuario, name="vista_verUsuario"),
    url(r'^lista_usuarios', views.vista_listaUsuarios, name="vista_listaUsuarios"),
    url(r'^(?P<getIdUsuario>[0-9]+)/editar_usuario/$', views.vista_editarUsuario, name="vista_editarUsuario"),
    url(r'^nuevo_usuario/$', views.vista_nuevoUsuario, name="vista_nuevoUsuario"),
    url(r'^eliminar_usuario/$', views.vista_eliminarUsuario, name="vista_eliminarUsuario"),
    url(r'^(?P<getIdUsuario>[0-9]+)/cambiar_contrasenha/$', views.vista_cambiarContrasenha, name="vista_cambiarContrasenha"),

    #PERMISOS
    url(r'^lista_permisos', views.vista_listaPermisos, name="vista_listaPermisos"),
    url(r'^nuevo_permiso/$', views.vista_nuevoPermiso, name="vista_nuevoPermiso"),
    url(r'^(?P<getIdPermiso>[0-9]+)/ver_permiso/$', views.vista_verPermiso, name="vista_verPermiso"),
    url(r'^(?P<getIdPermiso>[0-9]+)/editar_permiso/$', views.vista_editarPermiso, name="vista_editarPermiso"),

    #ROLES
    url(r'^(?P<getIdRol>[0-9]+)/ver_rol/$', views.vista_verRol, name="vista_verRol"),
    url(r'^lista_roles', views.vista_listaRoles, name="vista_listaRoles"),
    url(r'^nuevo_rol/$', views.vista_nuevoRol, name="vista_nuevoRol"),
    url(r'^(?P<getIdRol>[0-9]+)/editar_rol/$', views.vista_editarRol, name="vista_editarRol"),

    #USER STORY
    url(r'^(?P<idP>[0-9]+)/nuevo_us/$', views.vista_crear_userstory, name="vista_crear_userstory"),
    url(r'^eliminar_us/$', views.vista_eliminarUS, name="vista_eliminarUS"),
    url(r'^(?P<idP>[0-9]+)/consultar_us/(?P<idUs>[0-9]+)/$', views.vista_consultar_us, name="vista_consultar_us"),
    url(r'^(?P<idP>[0-9]+)/lista_us/$', views.vista_lista_us, name="vista_lista_us"),
    url(r'^(?P<idP>[0-9]+)/modificar_us/(?P<idUs>[0-9]+)/$', views.vista_modificar_us, name="vista_modificar_us"),
    #url(r'^(?P<idP>[0-9]+)/agregar_developer_us/(?P<idUs>[0-9]+)/$', views.vista_agregar_developer_us, name="vista_agregar_developer_us"), se paso a la parte de Sprint
    url(r'^(?P<idP>[0-9]+)/avance_us/(?P<idUs>[0-9]+)/$', views.vista_registrar_avance_us, name="vista_registrar_avance_us"),
    url(r'^(?P<idP>[0-9]+)/subir_archivo/(?P<idUs>[0-9]+)/$', views.vista_subirArchivo, name="vista_subirArchivo"),
    url(r'^eliminar_archivo/$', views.vista_eliminarArchivo, name="vista_eliminarArchivo"),
    url(r'^eliminar_nota/$', views.vista_eliminarNota, name="vista_eliminarNota"),

    #formularios
    url(r'^eliminar_permiso/$', views.vista_eliminarPermiso, name="vista_eliminarPermiso"),
    url(r'^eliminar_rol/$', views.vista_eliminarRol, name="vista_eliminarRol"),

    #SPRINTS
    url(r'^(?P<idP>[0-9]+)/crear_sprint/$', views.vista_crear_sprint,name="vista_crear_sprint"),
    url(r'^(?P<idP>[0-9]+)/lista_sprint', views.vista_lista_sprint, name="vista_lista_sprint"),
    url(r'^(?P<idP>[0-9]+)/consultar_sprint/(?P<idS>[0-9]+)$', views.vista_consultar_sprint, name="vista_consultar_sprint"),
    url(r'^(?P<idP>[0-9]+)/modificar_sprint/(?P<idS>[0-9]+)$', views.vista_modificar_sprint, name="vista_modificar_sprint"),
    url(r'^eliminar_sprint/$', views.vista_eliminar_sprint, name="vista_eliminar_sprint"),
    url(r'^(?P<idP>[0-9]+)/agregar_us/(?P<idS>[0-9]+)$', views.vista_agregar_us, name="vista_agregar_us"),
    url(r'^(?P<idP>[0-9]+)/agregar_developers_sprint/(?P<idS>[0-9]+)$', views.vista_agregar_developer_sprint, name="vista_agregar_developer_sprint"),
    url(r'^(?P<idP>[0-9]+)/agregar_developer_us/(?P<idS>[0-9]+)/(?P<idUs>[0-9]+)/$', views.vista_agregar_developer_us, name="vista_agregar_developer_us"),
    url(r'^(?P<idP>[0-9]+)/agregar_horas_trabajo_sprint/(?P<idS>[0-9]+)$', views.vista_asignar_horas_trabajo, name="vista_asignar_horas_trabajo"),
    url(r'^(?P<idP>[0-9]+)/ejecutar_sprint/(?P<idS>[0-9]+)$', views.vista_ejecutar_sprint, name="vista_ejecutar_sprint"),
    url(r'^finalizar_sprint/$', views.vista_finalizar_sprint, name="vista_finalizar_sprint"),

    #flujos
    url(r'^(?P<idP>[0-9]+)/lista_flujos', views.vista_listaFlujos, name="vista_listaFlujos"),
    url(r'^(?P<idP>[0-9]+)/nuevo_flujo/$', views.vista_nuevoFlujo, name="vista_nuevoFlujo"),
    url(r'^ver_flujo/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_verFlujo, name="vista_verFlujo"),
    url(r'^editar_flujo/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_editarFlujo, name="vista_editarFlujo"),
    url(r'^editar_estadoUS/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/(?P<idUs>[0-9]+)/$', views.vista_editarEstadoUS, name="vista_editarEstadoUS"),
    url(r'^editar_actividad/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/(?P<idActividad>[0-9]+)/$', views.vista_editarActividad,name="vista_editarActividad"),
    url(r'^agregar_us_a_flujo/(?P<idP>[0-9]+)/(?P<idUS>[0-9]+)/(?P<idS>[0-9]+)$', views.vista_agregarUSaFlujo,name="vista_agregarUSaFlujo"),

    #kanban
    url(r'^lista_kanban/(?P<idP>[0-9]+)/$', views.vista_listaKanban, name="vista_listaKanban"),
    url(r'^ver_kanban/(?P<idP>[0-9]+)/(?P<idFlujo>[0-9]+)/$', views.vista_verKanban, name="vista_verKanban"),
]

sgp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("autenticacion.urls", namespace='autenticacion')),
    url(r'^', include("proyecto.urls", namespace='proyecto')),
]

templates/html/us/agregar_desarrollador_us.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    Developer del User Story
{% endblock %}
{% block header %}
{% endblock %}
{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Developer del User Story
                <small></small>
            </h1>
            <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                            </li>
                            {% if request.user.is_staff %}
                             <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de Proyectos</a>
                            </li>
                            {% else %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_mis_proyectos' %}">Mis Proyectos</a>
                            </li>
                            {% endif %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_proyecto' proyecto.id %}">Consulta Proyecto</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_lista_sprint' idP %}">Sprint Backlog</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_sprint' idP idS %}">Consulta de Sprint</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-list"></i> Developer del User Story
                            </li>
            </ol>
        </div>
        <div class="col-lg-6">
            <form action="" method="post">
                {% csrf_token %}
                    <div class="form-group">
                        <label>Elegir Developer: </label>
                        <select class="form-control" id="idNombre_Developer" name="idNombre_Developer">
                            {% for developer in lista_developers_proyecto %}
                                <option>{{ developer.usuario.user.username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                <br>
                <button type="submit" class="btn btn-success">Guardar</button>
                <button type="reset" class="btn btn-default">Limpiar datos</button>
                <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_consultar_sprint' idP idS %}">Cancelar</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/html/us/avance_us.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    Registrar avance
{% endblock %}
{% block header %}
{% endblock %}
{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Registrar avance en el User Story
                <small></small>
            </h1>
            <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                            </li>
                            {% if request.user.is_staff %}
                             <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de Proyectos</a>
                            </li>
                            {% else %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_mis_proyectos' %}">Mis Proyectos</a>
                            </li>
                            {% endif %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_proyecto' proyecto.id %}">Consulta Proyecto</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_lista_us' idP %}">Product Backlog</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-list"></i> Registrar Avance
                            </li>
            </ol>
        </div>
        <div class="col-lg-5">
            <form action="" method="post">
                {% csrf_token %}
                <ul>
                    <li><label>Tiempo de duración estimado del UserStory en horas:  </label>{{ us.tiempo_estimado }}</li>
                    <br>
                    <li><label>Tiempo dedicado al UserStory en horas:</label></li>
                    <input class="form-control" type="number" step="any" id="tiempo_dedicado_form" name="tiempo_dedicado_form" required>
                    <br>
                </ul>
                <button type="submit" class="btn btn-success" >Guardar</button>
                <button type="reset" class="btn btn-default">Datos originales</button>
                <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_lista_us' idP%}">Cancelar</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/html/us/consultar_us.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    Detalle US
{% endblock %}
{% block header %}
    <script>
        function eliminarArchivo(idArchivo) {
            bootbox.dialog({
                message: "¿Realmente desea eliminar el archivo adjunto ?",
                title: "Eliminar archivo",
                buttons: {
                    success: {
                        label: "Sí",
                        className: "btn-success",
                        callback: function () {

                            var request = $.ajax({
                                type: "POST",
                                url: "{% url 'proyecto:vista_eliminarArchivo' %}",
                                data: {
                                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                                    "idArchivo": idArchivo
                                },
                            });
                            request.done(function (response) {
                                alert("Archivo eliminado..");
                                window.location = "{% url 'proyecto:vista_listaPermisos' %}"
                            });
                        }
                    },
                    danger: {
                        label: "No",
                        className: "btn-danger"
                    }
                }
            });
        }
        function eliminarNota(idArchivo) {
            bootbox.dialog({
                message: "¿Realmente desea eliminar la nota adjunta ?",
                title: "Eliminar nota",
                buttons: {
                    success: {
                        label: "Sí",
                        className: "btn-success",
                        callback: function () {

                            var request = $.ajax({
                                type: "POST",
                                url: "{% url 'proyecto:vista_eliminarNota' %}",
                                data: {
                                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                                    "idNota": idArchivo
                                },
                            });
                            request.done(function (response) {
                                alert("Nota eliminada..");
                                window.location = "{% url 'proyecto:vista_listaPermisos' %}"
                            });
                        }
                    },
                    danger: {
                        label: "No",
                        className: "btn-danger"
                    }
                }
            });
        }


    </script>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <script> generate("success","{{ message }}") </script>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Detalles del US
                <small></small>
            </h1>

            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                </li>
                {% if request.user.is_staff %}
                    <li>
                        <i class="fa fa-table"></i> <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de
                        Proyectos</a>
                    </li>
                {% else %}
                    <li>
                        <i class="fa fa-table"></i> <a href="{% url 'proyecto:vista_mis_proyectos' %}">Mis Proyectos</a>
                    </li>
                {% endif %}
                <li>
                    <i class="fa fa-table"></i> <a href="{% url 'proyecto:vista_consultar_proyecto' proyecto.id %}">Consulta
                    Proyecto</a>
                </li>
                <li>
                    <i class="fa fa-table"></i> <a href="{% url 'proyecto:vista_lista_us' idP %}">Product Backlog</a>
                </li>
                <li class="active">
                    <i class="fa fa-list"></i> Consulta User Story
                </li>

            </ol>
        </div>
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" align="center"> {{ proyecto.nombre_largo }} </h3>
                </div>
                <div class="panel-body">
                    <ul>
                        <li><strong>Id del US:</strong> {{ us.id }} </li>
                        <br>
                        <li><strong>Descripción corta del User Story:</strong> {{ us.descripcion_corta }} </li>
                        <br>
                        <li><strong>Descripción larga del User Story:</strong> {{ us.descripcion_larga }} </li>
                        <br>
                        <li><strong>Tiempo estimado del User Story en horas:</strong> {{ us.tiempo_estimado }} </li>
                        <br>
                        <li><strong>Developer del User Story:</strong> {{ pb.usuario.user.username }} </li>
                        <br>
                        <li><strong>Tiempo dedicado al User Story en horas:</strong> {{ us.tiempo_dedicado }} </li>
                        <br>
                        <li><strong>Prioridad del User Story:</strong> {{ us.get_prioridad_verbose }} </li>
                        <br>
                        <li><strong>Valor de Negocio del User Story:</strong> {{ us.valor_de_negocios }} </li>
                        <br>
                        <li><strong>Valor Tecnico del User Story:</strong> {{ us.valor_tecnico }} </li>
                        <br>
                        <li><strong>Tiempo de creación del User Story:</strong> {{ us.timestamp }} </li>
                        <br>
                        <br>
                        <li><strong>Archivos adjuntos:</strong></li>
                        <br>
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                            <tr>
                                <th>
                                    <center>Links de descarga</center>
                                </th>
                             <th>
                            <center>Adjunto por</center>
                            </th>
                             <th>
                            <center>Fecha de creación</center>
                            </th>
                                 {% if 'eliminar_archivo' in permisosAsociados and esDeveloper or esScrumMaster%}
                                <th>
                                    <center>Archivo</center>
                                </th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for file in files %}
                                <tr>
                                    <td align="center"><a target="_blank" href="data:;base64,{{ file.archivo }}"
                                                          download="{{ file.nombreArchivo }}">{{ file.nombreArchivo }}</a>
                                    </td>
                                    <td align="center">{{ file.user.username }}</td>
                                    <td align="center">{{ file.timestamp }}</td>
                                    {% if 'eliminar_archivo' in permisosAsociados and esDeveloper or esScrumMaster%}
                                    <td align="center">
                                        <a href=javascript:eliminarArchivo({{ file.id }}) id="btnEliminar" class="btn btn-danger">Eliminar</a>
                                    </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <li><strong>Notas adjuntas:</strong></li>
                        <br>
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                            <tr>
                                <th>
                                    <center>Contenido</center>

                                </th>
                            <th>
                            <center>Creada por</center>
                            </th>
                             <th>
                            <center>Fecha de creación</center>
                            </th>
                                {% if 'eliminar_nota' in permisosAsociados and esDeveloper or esScrumMaster%}
                                <th>
                                    <center>Nota</center>
                                </th>
                                 {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for nota in notas %}
                                <tr>
                                    <td>{{ nota.nota }}</td>
                                    <td align="center">{{ nota.user.username }}</td>
                                    <td align="center">{{ nota.timestamp }}</td>
                                    {% if 'eliminar_nota' in permisosAsociados and esDeveloper or esScrumMaster%}
                                     <td align="center">
                                        <a href=javascript:eliminarNota({{ nota.id }}) class="btn btn-danger">Eliminar</a>
                                    </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <li><strong>Log de eventos:</strong></li>
                        <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Descripción del evento</th>
                                        <th>Hora y fecha del evento</th>

                                    </tr>
                                </thead>
                                <tbody>
                                {% for log in lista_log %}
                                    <tr>

                                        <td>{{ log.descripcion }}</td>
                                        <td>{{ log.timestamp }}</td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                    </ul>

                </div>
            </div>
            {% if 'registrar_avances_us' in permisosAsociados and pb.usuario.user.username == request.user.username %}
                <a class="btn btn-sm btn-default"
                   href="{% url 'proyecto:vista_registrar_avance_us' proyecto.id us.id %}">Registrar avances</a>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/html/us/listaArchivosYnotas.html
{% extends 'base.html' %}
{% block titulo %}
    Proyecto
{% endblock %}
{% block header %}
{% endblock %}
{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Adjuntar archivos y notas - User Story '{{ us.descripcion_corta }}'
                <small></small>
            </h1>
            <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                            </li>
                            {% if request.user.is_staff %}
                             <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de Proyectos</a>
                            </li>
                            {% else %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_mis_proyectos' %}">Mis Proyectos</a>
                            </li>
                            {% endif %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_proyecto' proyecto.id %}">Consulta Proyecto</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_lista_us' idP %}">Product Backlog</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-list"></i> Lista de Archivos adjuntos y notas.
                            </li>
            </ol>
        </div>
        <div class="col-lg-6">
            <form action="" method="post" name="form" id="form" enctype="multipart/form-data">
                {% csrf_token %}

                <label>Adjuntar archivos:</label>
               <input type="file" name="archivo" multiple="multiple">

                <br>
                <label>Adjuntar una nota:</label>
               <textarea class="form-control" rows="10" name="nota"></textarea>
                <br>

                <button type="submit" class="btn btn-success" >Guardar</button>



            </form>
        </div>

    </div>

{% endblock %}

templates/html/us/lista_us.html
{% extends 'base_para_proyecto.html' %}
{% block titulo %}
    Product Backlog
{% endblock %}
{% block header %}
    <script>
        function eliminarUS(idUS,nombreUS) {

            bootbox.dialog({
                message: "¿Realmente desea eliminar el User Story '"+nombreUS+"'?",
                title: "Eliminar User Story",
                buttons: {
                    success: {
                        label: "Sí",
                        className: "btn-success",
                        callback: function () {

                            var request = $.ajax({
                                type: "POST",
                                url: "{% url 'proyecto:vista_eliminarUS' %}",
                                data: {
                                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                                    "IDProyecto": {{ proyecto.id }},
                                    "IDUs": idUS
                                },
                            });
                            request.done(function (response) {
                                    alert("User Story eliminado..");
                                window.location="{% url 'proyecto:vista_lista_us' proyecto.id %}"
                            });
                        }
                    },
                    danger: {
                        label: "No",
                        className: "btn-danger"
                    }
                }
            });
        }
    </script>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <script> generate("success","{{ message }}") </script>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

{% block contenido %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Product Backlog
                <small></small>
            </h1>

            <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="{% url 'proyecto:vista_index' %}">Inicio</a>
                            </li>
                            {% if request.user.is_staff %}
                             <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_listar_proyectos' %}">Lista de Proyectos</a>
                            </li>
                            {% else %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_mis_proyectos' %}">Mis Proyectos</a>
                            </li>
                            {% endif %}
                            <li>
                                <i class="fa fa-table"></i>  <a href="{% url 'proyecto:vista_consultar_proyecto' proyecto.id %}">Consulta Proyecto</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-list"></i> Product Backlog
                            </li>
            </ol>
        </div>
        <div class="col-lg-9">
            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th><center>Descripción corta</center></th>
                                        <th><center>Descripción larga</center></th>
                                        <th><center>Prioridad</center></th>
                                        <th><center>User Story</center></th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for us in lista_us %}
                                    <tr>
                                        <td>{{ us.0.descripcion_corta }}</td>
                                        <td>{{ us.0.descripcion_larga }}</td>
                                        <td>{{ us.0.get_prioridad_verbose }}</td>
                                            <td>
                                                <center>
                                                    <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_consultar_us' proyecto.id us.0.id %}">Detalles</a>
                                                    {% if 'editar_us' in permisosAsociados %}
                                                    <a class="btn btn-sm btn-default" href="{% url 'proyecto:vista_modificar_us' proyecto.id us.0.id %}">Modificar</a>
                                                    {% endif %}
                                                    {% if us.1.id == user.id or user.id == scrum.id%}
                                                    <a class="btn btn-sm btn-success" href="{% url 'proyecto:vista_subirArchivo' proyecto.id us.0.id %}">Adjuntar archivos y notas</a>
                                                    {% endif %}
                                                    {% if 'eliminar_us' in permisosAsociados and us.0.asignado_a_sprint == False%}
                                                    <a href="javascript:eliminarUS({{us.0.id}},'{{us.0.descripcion_corta}}');" class="btn btn-sm btn-danger">Eliminar</a>
                                                    {% endif %}
                                                </center>
                                            </td>
                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
        </div>

    </div>

{% endblock %}